apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xwh5q6zlr-dotnet-basic
  janus-idp.io/tekton: xwh5q6zlr-dotnet-basic
  backstage.io/kubernetes-id: xwh5q6zlr-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xwh5q6zlr-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
